# Testing EUGENE package structure

**Authorship:**
Adam Klie, *04/06/2022*
***
**Description:**
Notebook to test the structure of EUGENE module importing
***
<div class="alert alert-block alert-warning">
<b>TODOs</b>:
<ul>
    <b><li></li></b>
    <b><li></li></b>
    <b><li></li></b>
    </ul>
</div>

# Set-up

In [3]:
# The classics
import pandas as pd
import numpy as np

# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
%autoreload 2

# Basic import
import eugene

In [4]:
eugene.__version__

'0.0.0'

# Settings

In [5]:
eugene.settings.datasetdir

PosixPath('/mnt/beegfs/users/aklie/projects/EUGENE/test/data')

# Dataset

## Random

In [6]:
eugene.datasets.generate_random_data?

Signature:
eugene.datasets.generate_random_data(
    num_seqs,
    seq_len,
    out_dir='./random_data/',
)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/datasets/_generate_data.py
Type:      function


## Preprocessed

In [7]:
eugene.datasets.get_dataset_info?

Signature: eugene.datasets.get_dataset_info()
Docstring:
Return DataFrame with info about builtin datasets.
Returns
-------
DataFrame
    Info about builtin datasets indexed by dataset name.
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/datasets/_datasets.py
Type:      function


In [8]:
eugene.datasets.Khoueiry10?

Signature: eugene.datasets.Khoueiry10(**kwargs: dict) -> pandas.core.frame.DataFrame
Docstring: Loads the Khoueiry10 dataset.
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/datasets/_datasets.py
Type:      function


# Dataloading

## I/O 

In [9]:
eugene.dl.load?

Object `eugene.dl.load` not found.


In [10]:
eugene.dl.load_csv?

Object `eugene.dl.load_csv` not found.


In [11]:
eugene.dl.load_fasta?

Object `eugene.dl.load_fasta` not found.


## Dataloaders

In [12]:
eugene.dl.dataloaders.SeqDataset?

Init signature: eugene.dl.dataloaders.SeqDataset(*args, **kwds)
Docstring:      Sequence based PyTorch dataset definition
Init docstring:
Args:
    seqs (iterable): list of sequences to serve as input into models
    names (iterable, optional): list of identifiers for sequences
    targets (iterable): aligned list of targets for each sequence
    rev_seqs (iterable, optional): Optional reverse complements of seqs
    transform (callable, optional): Optional transform to be applied
        on a sample.
File:           /mnt/beegfs/users/aklie/projects/EUGENE/eugene/dataloading/dataloaders/_SeqDataset.py
Type:           type
Subclasses:     


In [13]:
eugene.dl.dataloaders.SeqDataModule?

Init signature: eugene.dl.dataloaders.SeqDataModule(*args: Any, **kwargs: Any) -> 'LightningDataModule'
Docstring:     
A DataModule standardizes the training, val, test splits, data preparation and transforms. The main
advantage is consistent data splits, data preparation and transforms across models.

Example::

    class MyDataModule(LightningDataModule):
        def __init__(self):
            super().__init__()
        def prepare_data(self):
            # download, split, etc...
            # only called on 1 GPU/TPU in distributed
        def setup(self, stage):
            # make assignments here (val/train/test split)
            # called on every process in DDP
        def train_dataloader(self):
            train_split = Dataset(...)
            return DataLoader(train_split)
        def val_dataloader(self):
            val_split = Dataset(...)
            return DataLoader(val_split)
        def test_dataloader(self):
            test_split = Dataset(...)
            retur

## Config

In [14]:
eugene.dl.generate_data_config?

Signature: eugene.dl.generate_data_config(dataloader)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/dataloading/_generate_data_config.py
Type:      function


# Preprocessing

## Encode

In [15]:
eugene.pp.encodeDNA?

Signature: eugene.pp.encodeDNA(seq_vec, maxlen=None, seq_align='start')
Docstring:
Convert the DNA sequence into 1-hot-encoding numpy array
# Arguments
    seq_vec: list of chars
        List of sequences that can have different lengths
    maxlen: int or None,
        Should we trim (subset) the resulting sequence. If None don't trim.
        Note that trims wrt the align parameter.
        It should be smaller than the longest sequence.
    seq_align: character; 'end' or 'start'
        To which end should we align sequences?
# Returns
    3D numpy array of shape (len(seq_vec), trim_seq_len(or maximal sequence length if None), 4)
# Example
    ```python
        >>> sequence_vec = ['CTTACTCAGA', 'TCTTTA']
        >>> X_seq = encodeDNA(sequence_vec, seq_align="end", maxlen=8)
        >>> X_seq.shape
        (2, 8, 4)
        >>> print(X_seq)
        [[[0 0 0 1]
          [1 0 0 0]
          [0 1 0 0]
          [0 0 0 1]
          [0 1 0 0]
          [1 0 0 0]
          [0 0 1 0]
      

## Preprocess

In [16]:
eugene.pp.standardize_features?

Signature:
eugene.pp.standardize_features(
    train_X,
    test_X,
    indeces=None,
    stats_file=None,
)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/preprocessing/_dataset_preprocess.py
Type:      function


## Transforms

In [19]:
eugene.dl.ToTensor?

Init signature: eugene.dl.ToTensor(transpose=False)
Docstring:      Convert ndarrays in sample to Tensors.
File:           /mnt/beegfs/users/aklie/projects/EUGENE/eugene/dataloading/_transforms.py
Type:           type
Subclasses:     


# Models

## Fully connected network

In [20]:
eugene.models.FCN?

Init signature:
eugene.models.FCN(
    input_len,
    strand='ss',
    task='regression',
    aggr=None,
    fc_kwargs={},
)
Docstring:      Hooks to be used in LightningModule.
File:           /mnt/beegfs/users/aklie/projects/EUGENE/eugene/models/_fcn.py
Type:           type
Subclasses:     


## Convolutional network

In [21]:
eugene.models.CNN?

Init signature:
eugene.models.CNN(
    input_len,
    strand='ss',
    task='regression',
    aggr=None,
    conv_kwargs={},
    fc_kwargs={},
)
Docstring:      Hooks to be used in LightningModule.
File:           /mnt/beegfs/users/aklie/projects/EUGENE/eugene/models/_cnn.py
Type:           type
Subclasses:     


## Recurrent Network

In [22]:
eugene.models.RNN?

Init signature:
eugene.models.RNN(
    input_len,
    strand='ss',
    task='regression',
    aggr=None,
    rnn_kwargs={},
    fc_kwargs={},
)
Docstring:      Hooks to be used in LightningModule.
File:           /mnt/beegfs/users/aklie/projects/EUGENE/eugene/models/_rnn.py
Type:           type
Subclasses:     


## Hybrid CNN-RNN

In [23]:
eugene.models.Hybrid?

Init signature:
eugene.models.Hybrid(
    input_len,
    strand='ss',
    task='regression',
    aggr=None,
    conv_kwargs={},
    rnn_kwargs={},
    fc_kwargs={},
)
Docstring:      Hooks to be used in LightningModule.
File:           /mnt/beegfs/users/aklie/projects/EUGENE/eugene/models/_hybrid.py
Type:           type
Subclasses:     


# Train

In [23]:
eugene.train.PredictionWriter?

Init signature: eugene.train.PredictionWriter(output_dir: str, write_interval='epoch')
Docstring:     
Base class to implement how the predictions should be stored.

Args:
    write_interval: When to write.

Example::

    import torch
    from pytorch_lightning.callbacks import BasePredictionWriter

    class CustomWriter(BasePredictionWriter):

        def __init__(self, output_dir: str, write_interval: str):
            super().__init__(write_interval)
            self.output_dir

        def write_on_batch_end(
            self, trainer, pl_module: 'LightningModule', prediction: Any, batch_indices: List[int], batch: Any,
            batch_idx: int, dataloader_idx: int
        ):
            torch.save(prediction, os.path.join(self.output_dir, dataloader_idx, f"{batch_idx}.pt"))

        def write_on_epoch_end(
            self, trainer, pl_module: 'LightningModule', predictions: List[Any], batch_indices: List[Any]
        ):
            torch.save(predictions, os.path.join(self.out

# Predict

# Interpret

In [13]:
eugene.interpret.nn_explain?

Signature:
eugene.interpret.nn_explain(
    model,
    inputs,
    saliency_type,
    target=None,
    ref_type='zero',
    device='cpu',
    abs_value=False,
)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/interpret/_nn_explain.py
Type:      function


# Plotting

In [24]:
eugene.pl.pca?

Signature:
eugene.pl.pca(
    pc_data,
    pc1=0,
    pc2=1,
    color='b',
    loadings=None,
    labels=None,
    n=5,
)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/plotting/_plotting.py
Type:      function


In [25]:
eugene.pl.umap?

Signature:
eugene.pl.umap(
    umap_data,
    umap1=0,
    umap2=1,
    color='b',
    loadings=None,
    labels=None,
    n=5,
)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/plotting/_plotting.py
Type:      function


In [26]:
eugene.pl.skreeplot?

Signature: eugene.pl.skreeplot(pca_obj, n_comp=30)
Docstring:
Function to generate and output a Skree plot using matplotlib barplot
Parameters
----------
pca_obj : scikit-learn pca object
n_comp : number of components to show in the plot

Returns
-------
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/plotting/_plotting.py
Type:      function


In [27]:
eugene.pl.otxGenomeTracks?

Signature:
eugene.pl.otxGenomeTracks(
    seq,
    importance_scores=None,
    model_pred=None,
    seq_name=None,
    threshold=0.5,
    highlight=[],
    cmap=None,
    norm=None,
)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/plotting/_plotting.py
Type:      function


# External 

In [28]:
eugene.external.gkm_svm.get_scores?

Signature: eugene.external.gkm_svm.get_scores(fname)
Docstring: <no docstring>
File:      /mnt/beegfs/users/aklie/projects/EUGENE/eugene/external/gkm_svm/_gkm_svm.py
Type:      function


---