In [1]:
# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import eugene as eu

Global seed set to 13
2022-09-26 20:55:21.498172: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-26 20:55:21.724834: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-26 20:55:21.724866: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-26 20:55:21.758242: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-09-26 20:55:22.634552: W tensorfl

In [30]:
test_model = eu.models.Jores21CNN(input_len=66, output_dim=1)

In [38]:
test_model.biconv.kernels[0][0][0]

tensor([ 0.0612, -0.0536,  0.2887, -0.1920,  0.3159, -0.2874,  0.0552,  0.0625,
        -0.0778, -0.2019, -0.2042, -0.0334,  0.1407],
       grad_fn=<SelectBackward0>)

In [39]:
eu.models.init_weights(test_model)

Initializing Parameter containing:
tensor([[[ 0.0612, -0.0536,  0.2887,  ..., -0.2042, -0.0334,  0.1407],
         [-0.1950,  0.1743, -0.1812,  ..., -0.0642, -0.1494,  0.0763],
         [-0.0470,  0.1843, -0.0274,  ...,  0.0056, -0.1053, -0.1083],
         [ 0.0811, -0.2294, -0.4775,  ..., -0.1892, -0.1242, -0.0157]],

        [[ 0.0996, -0.0074,  0.3859,  ..., -0.1124, -0.0520,  0.1077],
         [ 0.4660,  0.0969, -0.0276,  ..., -0.1436,  0.2889,  0.1241],
         [ 0.0409, -0.2220, -0.1669,  ..., -0.2784,  0.0202, -0.4784],
         [ 0.0532,  0.0534,  0.0575,  ...,  0.2235,  0.1281, -0.2048]],

        [[-0.0023,  0.2004,  0.2376,  ...,  0.1524, -0.1352, -0.4274],
         [ 0.0683,  0.0976, -0.1108,  ..., -0.0626,  0.0666, -0.0328],
         [-0.2985,  0.0101, -0.2466,  ...,  0.0508,  0.0229, -0.0469],
         [ 0.2460,  0.0740,  0.4381,  ..., -0.0100,  0.0438,  0.0786]],

        ...,

        [[-0.0776, -0.1389,  0.0336,  ..., -0.1651,  0.2761, -0.1048],
         [ 0.0726,  0.

In [40]:
test_model.biconv.kernels[0][0][0]

tensor([-0.4188,  0.0741, -0.1926, -0.3829, -0.1939,  0.1521,  0.5470,  0.0652,
         0.0006,  0.1485, -0.0212, -0.0861,  0.2850],
       grad_fn=<SelectBackward0>)