# Testing `Jores21CNN` model class

**Authorship:**
Adam Klie, *07/31/2022*
***
**Description:**
Notebook for testing out the custom `Jores21CNN` model class.

In [21]:
import numpy as np
import pandas as pd
import torch

# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
%autoreload 2

In [22]:
import eugene as eu

# Instantiate a `Jores21CNN` model

In [89]:
model = eu.models.Jores21CNN(170, 1)
model

Jores21CNN(
  (hp_metric): R2Score()
  (biconv): BiConv1D()
  (conv): Conv1d(128, 128, kernel_size=(13,), stride=(1,), padding=same)
  (dropout): Dropout(p=0.15, inplace=False)
  (fc): Linear(in_features=21760, out_features=64, bias=True)
  (batchnorm): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=64, out_features=1, bias=True)
)

In [90]:
x = torch.randn(10, 4, 170)

In [91]:
model(x)

tensor([[0.4699],
        [0.8423],
        [1.1953],
        [1.1711],
        [0.7117],
        [0.0583],
        [1.0075],
        [0.9660],
        [0.5447],
        [0.7457]], grad_fn=<AddmmBackward0>)

In [92]:
core_promoter_elements = eu.utils.MinimalMEME('/cellar/users/aklie/projects/EUGENe/tests/_data/datasets/jores21/CPEs.meme')
tf_groups = eu.utils.MinimalMEME('/cellar/users/aklie/projects/EUGENe/tests/_data/datasets/jores21/TF-clusters.meme')
all_motifs = {**core_promoter_elements.motifs, **tf_groups.motifs}
len(all_motifs)

78

In [93]:
model.biconv.kernels[0][0]

tensor([[ 5.8025e-02,  2.6416e-02, -3.8535e-02, -1.0577e-02,  4.3315e-02,
          2.1613e-02, -1.7688e-02, -5.0108e-02,  4.6055e-02, -2.9319e-02,
         -3.8448e-02, -1.5185e-02, -1.7067e-03],
        [-4.1143e-03, -3.3956e-02,  6.2217e-04, -4.1170e-02,  4.2986e-02,
          2.0373e-02, -1.6676e-02,  2.3642e-02, -3.5047e-02,  4.6149e-02,
          5.6794e-03,  3.8404e-02,  6.6676e-05],
        [-2.6334e-02, -2.7681e-02, -2.8493e-02, -5.0077e-02,  4.9505e-02,
          1.5518e-02,  3.3436e-02,  4.9166e-02, -2.9328e-02,  1.6801e-02,
          4.0794e-02, -7.5571e-03,  3.2738e-02],
        [-4.1177e-02,  3.2498e-04,  4.9090e-02,  4.4912e-02,  4.4724e-03,
          1.5145e-02,  9.6194e-03,  3.7163e-02,  3.9051e-02, -3.7046e-03,
          3.5302e-02,  5.0088e-02, -2.5166e-02]])

In [94]:
eu.models.init_from_motifs(
    model, 
    all_motifs, 
    layer_name='biconv', 
    kernel_name='kernels',
    kernel_number=0
)

In [95]:
model.biconv.kernels[0][0]

tensor([[0.5100, 0.6300, 0.9960, 0.4940, 0.0400, 3.8720, 0.0080, 3.9680, 2.6120,
         3.8960, 1.3640, 2.7820, 0.5020],
        [1.5060, 1.5940, 1.2120, 2.6200, 0.0080, 0.0000, 0.0560, 0.0000, 0.0480,
         0.0000, 0.1120, 0.3260, 1.7280],
        [0.4780, 0.7960, 0.7880, 0.3020, 0.0080, 0.0000, 0.0240, 0.0080, 0.0080,
         0.0320, 0.1440, 0.4780, 1.2660],
        [1.5060, 0.9820, 1.0040, 0.5820, 3.9440, 0.1280, 3.9120, 0.0240, 1.3320,
         0.0720, 2.3820, 0.4140, 0.5020]])

In [96]:
model(x)

tensor([[1.3220],
        [0.1054],
        [1.1493],
        [0.2871],
        [1.2071],
        [0.4177],
        [1.4466],
        [0.3072],
        [0.6756],
        [0.6425]], grad_fn=<AddmmBackward0>)

In [28]:
from eugene.utils._motif import _create_kernel_matrix

In [46]:
model.__getattr__("biconv").kernels[0] = kern

In [40]:
model."biconv"

SyntaxError: invalid syntax (2592916639.py, line 1)

In [36]:
kern = model.biconv.kernels[0]

In [37]:
kern = _create_kernel_matrix((128, 4, 13), all_motifs)

In [56]:
model.conv.weight = torch.nn.Parameter(torch.randn(128, 128, 13))

In [57]:
model.conv.weight

Parameter containing:
tensor([[[-1.1160, -0.3325, -0.7744,  ...,  0.0685, -0.1617, -0.7123],
         [ 0.0985, -1.0684,  0.9452,  ...,  0.0340,  0.8200, -0.8049],
         [-0.3100, -1.2196, -0.4721,  ...,  0.7886,  0.2196,  2.7004],
         ...,
         [-1.1247, -0.0458, -0.4971,  ...,  0.4404, -1.2233, -0.1531],
         [ 0.6456, -0.5590, -1.2134,  ..., -0.5988, -0.2380, -0.2558],
         [-0.8898, -1.3874, -0.8575,  ..., -0.4385,  1.1100, -0.2351]],

        [[-0.7794,  0.8648, -0.3815,  ..., -1.6818,  0.1235,  1.6162],
         [ 0.7390, -1.7336,  0.4566,  ...,  0.1805, -0.2668,  0.9915],
         [ 0.9938, -0.0948,  1.4486,  ...,  1.2259, -0.0529,  0.5860],
         ...,
         [-0.9741, -2.5641, -0.8386,  ...,  0.6279, -2.0081, -1.0378],
         [-0.1105,  0.5527, -0.0749,  ..., -0.5626, -0.4269,  0.9372],
         [-0.6103,  2.6745,  0.2042,  ..., -1.4715, -0.0636,  0.8312]],

        [[-1.8713,  0.9585,  1.2868,  ...,  0.8011,  0.1002,  0.1813],
         [-0.8813, -0.4

In [104]:
core_promoter_elements = MinimalMEME('/cellar/users/aklie/projects/EUGENe/tests/_data/datasets/jores21/CPEs.meme')
tf_groups = MinimalMEME('/cellar/users/aklie/projects/EUGENe/tests/_data/datasets/jores21/TF-clusters.meme')
all_motifs = {**core_promoter_elements.motifs, **tf_groups.motifs}

In [122]:
kernel = torch.zeros(128, 4, 13)
nn.init.xavier_uniform_(kernel)

# overwrite part of kernel with pfms from motifs
for i, motif_id in enumerate(all_motifs):
    motif = all_motifs[motif_id]
    # convert PFM to PWM, assume equal background frequency of 0.25
    # truncates motifs longer than 13bp to 13bp
    kernel[i, :, :min(len(motif), kernel.shape[2])] = torch.tensor(motif.pfm[:min(len(motif), kernel.shape[2]), :] / 0.25).transpose(0, 1)

In [124]:
model.biconv.kernels[0] = kernel

In [125]:
model(x)

tensor([[-0.0013],
        [ 0.0682],
        [ 0.0221],
        [-0.0021],
        [ 0.0844],
        [ 0.1157],
        [ 0.0566],
        [ 0.2570],
        [-0.1326],
        [-0.1769]], grad_fn=<AddmmBackward0>)

In [18]:
core_promoter_elements = eu.utils.MinimalMEME('/cellar/users/aklie/projects/EUGENe/tests/_data/datasets/jores21/CPEs.meme')
tf_groups = eu.utils.MinimalMEME('/cellar/users/aklie/projects/EUGENe/tests/_data/datasets/jores21/TF-clusters.meme')
all_motifs = {**core_promoter_elements.motifs, **tf_groups.motifs}

AttributeError: module 'eugene.utils' has no attribute 'MinimalMEME'